INSERT  INTO
	data_base
      ( 
      id                            
      ,type                           
      ,username                       
      ,password                       
      ,driver                         
      ,url                            
      ,remarks                        
      ) 
values
      (
      :dataBase.id                            
      ,:dataBase.type                          
      ,:dataBase.username                      
      ,:dataBase.password                      
      ,:dataBase.driver                        
      ,:dataBase.url                           
      ,:dataBase.remarks                       
      )